# WaterFurnace Aurora ESPHome - Local Development Configuration
# 
# This configuration is for local development and testing. It loads the
# component from the local 'components' directory rather than GitHub.
#
# Hardware requirements:
#   - M5Stack Atom Lite (or other ESP32 board)
#   - RS-485 transceiver (MAX485, MAX3485, or similar)
#   - Connection to Aurora ABC board RS-485 port
#
# Wiring (M5Stack Atom Lite -> RS485 board -> Aurora):
#   Atom GPIO26 (TX) -> RS485 DI (TX)
#   Atom GPIO32 (RX) -> RS485 RO (RX)
#   Atom GPIO33      -> RS485 DE + RE (flow control, directly to GPIO if no auto)
#   3.3V/5V          -> RS485 VCC
#   GND              -> RS485 GND
#   RS485 A          -> Aurora RS-485 A (+)
#   RS485 B          -> Aurora RS-485 B (-)
#   GND              -> Aurora GND (shield)
#
# Serial settings: 19200 baud, 8 data bits, Even parity, 1 stop bit

substitutions:
  device_name: waterfurnace-aurora
  friendly_name: "WaterFurnace Aurora"
  # Hardware pins for M5Stack Atom Lite
  uart_tx_pin: GPIO26
  uart_rx_pin: GPIO32
  flow_control_pin: GPIO33
  # Modbus settings
  modbus_address: "1"
  update_interval: 5s

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging (baud_rate 0 disables serial logging - needed for M5 Atom)
logger:
  level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
api:

# Enable OTA updates  
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback"

captive_portal:

# Web server for local access
web_server:
  port: 80

# UART configuration for RS-485 communication
# Aurora uses: 19200 baud, 8 data bits, Even parity, 1 stop bit
uart:
  id: mod_bus
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}
  baud_rate: 19200
  parity: EVEN
  stop_bits: 1

# External components - load from local directory for development
external_components:
  - source:
      type: local
      path: components

# WaterFurnace Aurora component
# RS-485 flow control is handled directly by the component
# Hardware is auto-detected at startup. Use overrides below if auto-detection fails.
waterfurnace_aurora:
  id: aurora
  uart_id: mod_bus
  address: ${modbus_address}
  update_interval: ${update_interval}
  flow_control_pin: ${flow_control_pin}
  read_retries: 2  # Number of retries on read failure (default 2)
  # Hardware overrides (uncomment to force detection):
  # has_axb: true        # Force AXB accessory board detection
  # has_vs_drive: true   # Force VS drive detection (5/7-Series)
  # has_iz2: true        # Force IntelliZone 2 detection
  # num_iz2_zones: 3     # Force IZ2 zone count (1-6)

# =============================================================================
# CLIMATE ENTITIES
# =============================================================================

climate:
  # Main thermostat (for non-IZ2 systems only)
  # IMPORTANT: If you have IntelliZone 2 (IZ2), comment out this main thermostat
  # and uncomment the zone entries below. On IZ2 systems, the system-wide registers
  # read by this entity contain IZ2 controller data, not actual temperatures.
  - platform: waterfurnace_aurora
    id: aurora_thermostat
    name: "Heat Pump"
    aurora_id: aurora

  # IZ2 Zone climates (uncomment if you have IntelliZone 2)
  # Each zone appears as a separate climate entity in Home Assistant
  # When using IZ2 zones, comment out the main "Heat Pump" thermostat above.
  # - platform: waterfurnace_aurora
  #   id: aurora_zone_1
  #   name: "Zone 1"
  #   aurora_id: aurora
  #   zone: 1
  # - platform: waterfurnace_aurora
  #   id: aurora_zone_2
  #   name: "Zone 2"
  #   aurora_id: aurora
  #   zone: 2

# =============================================================================
# CONTROLS - SWITCHES
# =============================================================================

switch:
  - platform: waterfurnace_aurora
    aurora_id: aurora
    dhw_enabled:
      name: "DHW Enabled"

# =============================================================================
# CONTROLS - NUMBER INPUTS
# =============================================================================

number:
  - platform: waterfurnace_aurora
    aurora_id: aurora
    # DHW setpoint (100-140°F)
    dhw_setpoint:
      name: "DHW Setpoint"
    # Indoor Blower/ECM speed settings (1-12)
    blower_only_speed:
      name: "Indoor Blower Only Speed"
    lo_compressor_speed:
      name: "Low Compressor ECM Speed"
    hi_compressor_speed:
      name: "High Compressor ECM Speed"
    aux_heat_speed:
      name: "Aux Electric Heat ECM Speed"
    # Loop Pump speed settings (1-100%)
    pump_min_speed:
      name: "Loop Pump Minimum Speed"
    pump_max_speed:
      name: "Loop Pump Maximum Speed"
    # Fan intermittent timing (minutes)
    fan_intermittent_on:
      name: "Fan Intermittent On Time"
    fan_intermittent_off:
      name: "Fan Intermittent Off Time"
    # Humidity setpoints (%)
    humidification_target:
      name: "Humidification Setpoint"
    dehumidification_target:
      name: "Dehumidification Setpoint"

# =============================================================================
# SENSORS
# =============================================================================

sensor:
  - platform: waterfurnace_aurora
    aurora_id: aurora
    
    # Air temperatures
    entering_air_temperature:
      name: "Return Air Temperature"
    leaving_air_temperature:
      name: "Supply Air Temperature"
    ambient_temperature:
      name: "Ambient Temperature"
    outdoor_temperature:
      name: "Outdoor Temperature"
    
    # Water/loop temperatures
    entering_water_temperature:
      name: "Entering Water Temperature"
    leaving_water_temperature:
      name: "Leaving Water Temperature"
    
    # Setpoints (read-only sensors)
    heating_setpoint:
      name: "Heating Setpoint"
    cooling_setpoint:
      name: "Cooling Setpoint"
    
    # Humidity
    humidity:
      name: "Humidity"
    
    # DHW (Domestic Hot Water)
    dhw_temperature:
      name: "DHW Temperature"
    dhw_setpoint:
      name: "DHW Setpoint"
    
    # Compressor / VS Drive
    compressor_speed:
      name: "Compressor Speed"
    compressor_desired_speed:
      name: "Compressor Desired Speed"
    
    # Pressures
    discharge_pressure:
      name: "Discharge Pressure"
    suction_pressure:
      name: "Suction Pressure"
    loop_pressure:
      name: "Loop Pressure"
    
    # Refrigeration
    eev_open_percentage:
      name: "EEV Open Percentage"
    superheat_temperature:
      name: "Superheat Temperature"
    subcool_temperature:
      name: "Subcool Temperature"
    discharge_temperature:
      name: "Discharge Temperature"
    suction_temperature:
      name: "Suction Temperature"
    heating_liquid_line_temperature:
      name: "Heating Liquid Line Temperature"
    saturated_condenser_temperature:
      name: "Saturated Condenser Temperature"
    fp1_temperature:
      name: "FP1 Temperature"
    fp2_temperature:
      name: "FP2 Temperature"
    
    # VS Drive temperatures
    vs_drive_temperature:
      name: "VS Drive Temperature"
    vs_inverter_temperature:
      name: "VS Inverter Temperature"
    vs_ambient_temperature:
      name: "VS Compressor Ambient Temperature"
    saturated_evaporator_discharge_temperature:
      name: "Saturated Evaporator Discharge Temperature"
    
    # VS Drive additional
    vs_fan_speed:
      name: "VS Fan Speed"
    vs_compressor_watts:
      name: "VS Compressor Power"
    
    # Aux electric heat
    aux_heat_stage:
      name: "Aux Electric Heat Stage"
    
    # Energy / Power
    line_voltage:
      name: "Line Voltage"
    total_watts:
      name: "Total Unit Power"
    compressor_watts:
      name: "Compressor Power"
    blower_watts:
      name: "Indoor Blower Power"
    aux_heat_watts:
      name: "Aux Electric Heat Power"
    pump_watts:
      name: "Loop Pump Power"
    heat_of_extraction:
      name: "Heat of Extraction"
    heat_of_rejection:
      name: "Heat of Rejection"
    
    # Loop / Water flow
    waterflow:
      name: "Loop Flow Rate"
    
    # Indoor Blower/ECM speeds
    blower_speed:
      name: "Indoor Blower Speed"
    blower_only_speed:
      name: "Indoor Blower Only Speed Setting"
    lo_compressor_speed:
      name: "Low Compressor ECM Speed Setting"
    hi_compressor_speed:
      name: "High Compressor ECM Speed Setting"
    aux_heat_speed:
      name: "Aux Electric Heat ECM Speed Setting"
    
    # Loop Pump speeds
    pump_speed:
      name: "Loop Pump Speed"
    pump_min_speed:
      name: "Loop Pump Minimum Speed Setting"
    pump_max_speed:
      name: "Loop Pump Maximum Speed Setting"
    
    # Humidity setpoints (read-only sensor versions)
    humidification_target:
      name: "Humidification Setpoint"
    dehumidification_target:
      name: "Dehumidification Setpoint"
    
    # System status
    line_voltage_setting:
      name: "Line Voltage Setting"
    anti_short_cycle:
      name: "Anti-Short-Cycle Countdown"
    fault_code:
      name: "Fault Code"
    
    # IZ2 desired speed sensors (uncomment if you have IntelliZone 2)
    # iz2_compressor_speed:
    #   name: "IZ2 Desired Compressor Speed"
    # iz2_blower_speed:
    #   name: "IZ2 Desired Blower Speed"
    
    # Derived sensors (computed on-device)
    cop:
      name: "Coefficient of Performance"
    water_delta_t:
      name: "Water Delta-T"
    approach_temperature:
      name: "Approach Temperature"

  # WiFi signal strength
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  # Uptime sensor
  - platform: uptime
    name: "Uptime"

# =============================================================================
# BINARY SENSORS
# =============================================================================

binary_sensor:
  - platform: waterfurnace_aurora
    aurora_id: aurora
    
    # Running states
    compressor_running:
      name: "Compressor Running"
    blower_running:
      name: "Indoor Blower Running"
    aux_heat_running:
      name: "Aux Electric Heat Running"
    dhw_running:
      name: "DHW Running"
    loop_pump_running:
      name: "Loop Pump Running"
    humidifier_running:
      name: "Humidifier Running"
    dehumidifier_running:
      name: "Dehumidifier Running"
    
    # Fault/problem states
    lockout:
      name: "Lockout"
      device_class: problem
    low_pressure_switch:
      name: "Low Pressure Switch"
      device_class: problem
    high_pressure_switch:
      name: "High Pressure Switch"
      device_class: problem
    emergency_shutdown:
      name: "Emergency Shutdown"
      device_class: problem
    load_shed:
      name: "Load Shed Active"

  # Connection status
  - platform: status
    name: "Status"

# =============================================================================
# TEXT SENSORS
# =============================================================================

text_sensor:
  - platform: waterfurnace_aurora
    aurora_id: aurora
    
    # Mode/status
    current_mode:
      name: "Current Mode"
    hvac_mode:
      name: "HVAC Mode"
    fan_mode:
      name: "Fan Mode"
    
    # Fault information
    fault_description:
      name: "Fault Description"
    fault_history:
      name: "Fault History"
    
    # Device information
    model_number:
      name: "Model Number"
    serial_number:
      name: "Serial Number"
    
    # VS Drive status
    vs_derate:
      name: "VS Drive Derate"
    vs_safe_mode:
      name: "VS Drive Safe Mode"
    vs_alarm:
      name: "VS Drive Alarm"
    
    # AXB status
    axb_inputs:
      name: "AXB Inputs"
    
    # Hardware info
    pump_type:
      name: "Pump Type"

  # ESPHome version
  - platform: version
    name: "ESPHome Version"

# =============================================================================
# BUTTONS
# =============================================================================

button:
  - platform: waterfurnace_aurora
    aurora_id: aurora
    clear_fault_history:
      name: "Clear Fault History"

  - platform: restart
    name: "Restart"
