substitutions:
  uart_tx_pin: GPIO17
  uart_rx_pin: GPIO16
  flow_control_pin: GPIO4
  modbus_address: "1"
  update_interval: 5s

external_components:
  - source:
      type: git
      url: https://github.com/daemonp/esphome_waterfurnace_aurora
      ref: master
    components: [ waterfurnace_aurora ]

uart:
  id: mod_bus
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}
  baud_rate: 19200
  parity: EVEN
  stop_bits: 1

# RS485 flow control is now handled directly by the component
# The flow_control_pin switches to HIGH during TX and LOW during RX

waterfurnace_aurora:
  id: aurora
  uart_id: mod_bus
  address: ${modbus_address}
  update_interval: ${update_interval}
  flow_control_pin: ${flow_control_pin}

climate:
  # Main thermostat (for non-IZ2 systems, or whole-system control)
  - platform: waterfurnace_aurora
    id: aurora_thermostat
    name: "Heat Pump"
    aurora_id: aurora

  # IZ2 Zone climates (uncomment if you have IntelliZone 2)
  # Each zone appears as a separate climate entity in Home Assistant
  # - platform: waterfurnace_aurora
  #   id: aurora_zone_1
  #   name: "Zone 1"
  #   aurora_id: aurora
  #   zone: 1
  # - platform: waterfurnace_aurora
  #   id: aurora_zone_2
  #   name: "Zone 2"
  #   aurora_id: aurora
  #   zone: 2
  # - platform: waterfurnace_aurora
  #   id: aurora_zone_3
  #   name: "Zone 3"
  #   aurora_id: aurora
  #   zone: 3
  # - platform: waterfurnace_aurora
  #   id: aurora_zone_4
  #   name: "Zone 4"
  #   aurora_id: aurora
  #   zone: 4
  # - platform: waterfurnace_aurora
  #   id: aurora_zone_5
  #   name: "Zone 5"
  #   aurora_id: aurora
  #   zone: 5
  # - platform: waterfurnace_aurora
  #   id: aurora_zone_6
  #   name: "Zone 6"
  #   aurora_id: aurora
  #   zone: 6

switch:
  - platform: waterfurnace_aurora
    aurora_id: aurora
    dhw_enabled:
      name: "DHW Enabled"

number:
  - platform: waterfurnace_aurora
    aurora_id: aurora
    dhw_setpoint:
      name: "DHW Setpoint"
    # Blower/ECM speed settings (1-12)
    blower_only_speed:
      name: "Blower Only Speed Setting"
    lo_compressor_speed:
      name: "Low Compressor Speed Setting"
    hi_compressor_speed:
      name: "High Compressor Speed Setting"
    aux_heat_speed:
      name: "Aux Heat Speed Setting"
    # Pump speed settings (1-100%)
    pump_min_speed:
      name: "Pump Min Speed Setting"
    pump_max_speed:
      name: "Pump Max Speed Setting"
    # Fan intermittent timing
    fan_intermittent_on:
      name: "Fan Intermittent On Time"
    fan_intermittent_off:
      name: "Fan Intermittent Off Time"
    # Humidity targets
    humidification_target:
      name: "Humidification Target"
    dehumidification_target:
      name: "Dehumidification Target"

sensor:
  - platform: waterfurnace_aurora
    aurora_id: aurora
    entering_air_temperature:
      name: "Entering Air Temperature"
    leaving_air_temperature:
      name: "Leaving Air Temperature"
    ambient_temperature:
      name: "Ambient Temperature"
    outdoor_temperature:
      name: "Outdoor Temperature"
    entering_water_temperature:
      name: "Entering Water Temperature"
    leaving_water_temperature:
      name: "Leaving Water Temperature"
    heating_setpoint:
      name: "Heating Setpoint"
    cooling_setpoint:
      name: "Cooling Setpoint"
    humidity:
      name: "Relative Humidity"
    dhw_temperature:
      name: "DHW Temperature"
    dhw_setpoint:
      name: "DHW Setpoint"
    compressor_speed:
      name: "Compressor Speed"
    discharge_pressure:
      name: "Discharge Pressure"
    suction_pressure:
      name: "Suction Pressure"
    eev_open_percentage:
      name: "EEV Open Percentage"
    superheat_temperature:
      name: "Superheat Temperature"
    line_voltage:
      name: "Line Voltage"
    total_watts:
      name: "Total Power"
    compressor_watts:
      name: "Compressor Power"
    blower_watts:
      name: "Blower Power"
    aux_heat_watts:
      name: "Aux Heat Power"
    pump_watts:
      name: "Pump Power"
    waterflow:
      name: "Loop Flow Rate"
    loop_pressure:
      name: "Loop Pressure"
    fault_code:
      name: "Fault Code"
    fp1_temperature:
      name: "FP1 Temperature"
    fp2_temperature:
      name: "FP2 Temperature"
    line_voltage_setting:
      name: "Line Voltage Setting"
    anti_short_cycle:
      name: "Anti-Short-Cycle Countdown"
    compressor_desired_speed:
      name: "Compressor Desired Speed"
    discharge_temperature:
      name: "Discharge Temperature"
    suction_temperature:
      name: "Suction Temperature"
    vs_drive_temperature:
      name: "VS Drive Temperature"
    vs_inverter_temperature:
      name: "VS Inverter Temperature"
    blower_speed:
      name: "Blower Speed"
    blower_only_speed:
      name: "Blower Only Speed Setting"
    lo_compressor_speed:
      name: "Low Compressor Speed Setting"
    hi_compressor_speed:
      name: "High Compressor Speed Setting"
    aux_heat_speed:
      name: "Aux Heat Speed Setting"
    pump_speed:
      name: "Pump Speed"
    pump_min_speed:
      name: "Pump Min Speed Setting"
    pump_max_speed:
      name: "Pump Max Speed Setting"
    heating_liquid_line_temperature:
      name: "Heating Liquid Line Temperature"
    saturated_condenser_temperature:
      name: "Saturated Condenser Temperature"
    subcool_temperature:
      name: "Subcool Temperature"
    heat_of_extraction:
      name: "Heat of Extraction"
    heat_of_rejection:
      name: "Heat of Rejection"
    humidification_target:
      name: "Humidification Target Sensor"
    dehumidification_target:
      name: "Dehumidification Target Sensor"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"

binary_sensor:
  - platform: waterfurnace_aurora
    aurora_id: aurora
    compressor_running:
      name: "Compressor Running"
    blower_running:
      name: "Blower Running"
    aux_heat_running:
      name: "Aux Heat Running"
    dhw_running:
      name: "DHW Running"
    loop_pump_running:
      name: "Loop Pump Running"
    lockout:
      name: "Lockout"
      device_class: problem
    humidifier_running:
      name: "Humidifier Running"
    dehumidifier_running:
      name: "Dehumidifier Running"
    low_pressure_switch:
      name: "Low Pressure Switch"
      device_class: problem
    high_pressure_switch:
      name: "High Pressure Switch"
      device_class: problem
    emergency_shutdown:
      name: "Emergency Shutdown"
      device_class: problem
    load_shed:
      name: "Load Shed Active"
  
  - platform: status
    name: "Status"

text_sensor:
  - platform: waterfurnace_aurora
    aurora_id: aurora
    current_mode:
      name: "Current Mode"
    hvac_mode:
      name: "HVAC Mode"
    fan_mode:
      name: "Fan Mode"
    fault_description:
      name: "Fault Description"
    model_number:
      name: "Model Number"
    serial_number:
      name: "Serial Number"
    fault_history:
      name: "Fault History"
    vs_derate:
      name: "VS Drive Derate"
    vs_safe_mode:
      name: "VS Drive Safe Mode"
    vs_alarm:
      name: "VS Drive Alarm"
    axb_inputs:
      name: "AXB Inputs"

  - platform: version
    name: "ESPHome Version"

button:
  - platform: waterfurnace_aurora
    aurora_id: aurora
    clear_fault_history:
      name: "Clear Fault History"

  - platform: restart
    name: "Restart"
